id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Resolution - Duplicate
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: Resolution - Answered
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: Resolution - External
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: Resolution - Fixed
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: Resolution - Won't Fix
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: Need Repro Info
      - noActivitySince:
          days: 14
      - isNotLabeledWith:
          label: Issue - Bug
      actions:
      - addReply:
          reply: Closing due to inactivity
      - closeIssue
    eventResponderTasks: []
onFailure: 
onSuccess: 
