<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>
    <ModuleVersion>1.25.0</ModuleVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <PropertyGroup Condition="'$(DisableEngineRetries)' == 'true'">
    <DefineConstants>$(DefineConstants);DISABLE_ENGINE_RETRIES</DefineConstants>
  </PropertyGroup>
</Project>
