//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.Powershell.ScriptAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Windows.Powershell.ScriptAnalyzer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking assembly file &apos;{0}&apos; ....
        /// </summary>
        internal static string CheckAssemblyFile {
            get {
                return ResourceManager.GetString("CheckAssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking module &apos;{0}&apos; ....
        /// </summary>
        internal static string CheckModuleName {
            get {
                return ResourceManager.GetString("CheckModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandInfo not found for function: {0}.
        /// </summary>
        internal static string CommandInfoNotFound {
            get {
                return ResourceManager.GetString("CommandInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes all diagnostics to WriteObject..
        /// </summary>
        internal static string DefaultLoggerDescription {
            get {
                return ResourceManager.GetString("DefaultLoggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteObjects.
        /// </summary>
        internal static string DefaultLoggerName {
            get {
                return ResourceManager.GetString("DefaultLoggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find file &apos;{0}&apos;..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the path &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No loggers found..
        /// </summary>
        internal static string LoggersNotFound {
            get {
                return ResourceManager.GetString("LoggersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find rule extension &apos;{0}&apos;..
        /// </summary>
        internal static string MissingRuleExtension {
            get {
                return ResourceManager.GetString("MissingRuleExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error in file {0}:  {1} at line {2} column {3}..
        /// </summary>
        internal static string ParserErrorFormat {
            get {
                return ResourceManager.GetString("ParserErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many parser errors in {0}. Please correct them before running ScriptAnalyzer..
        /// </summary>
        internal static string ParserErrorMessage {
            get {
                return ResourceManager.GetString("ParserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find analyzer rules..
        /// </summary>
        internal static string RulesNotFound {
            get {
                return ResourceManager.GetString("RulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing file: {0}.
        /// </summary>
        internal static string VerboseFileMessage {
            get {
                return ResourceManager.GetString("VerboseFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0} rule..
        /// </summary>
        internal static string VerboseRunningMessage {
            get {
                return ResourceManager.GetString("VerboseRunningMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rule Error &apos;{0}&apos;..
        /// </summary>
        internal static string RuleError
        {
            get
            {
                return ResourceManager.GetString("RuleErrorMessage", resourceCulture);
            }
        }
    }
}
