//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.PowerShell.ScriptAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Windows.PowerShell.ScriptAnalyzer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking assembly file &apos;{0}&apos; ....
        /// </summary>
        internal static string CheckAssemblyFile {
            get {
                return ResourceManager.GetString("CheckAssemblyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking module &apos;{0}&apos; ....
        /// </summary>
        internal static string CheckModuleName {
            get {
                return ResourceManager.GetString("CheckModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandInfo not found for function: {0}.
        /// </summary>
        internal static string CommandInfoNotFound {
            get {
                return ResourceManager.GetString("CommandInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Argument should not be null.&quot;..
        /// </summary>
        internal static string ConfigurableScriptRuleNRE {
            get {
                return ResourceManager.GetString("ConfigurableScriptRuleNRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cannot find a ConfigurableRuleProperty attribute on property {0}&quot;..
        /// </summary>
        internal static string ConfigurableScriptRulePropertyHasNotAttribute {
            get {
                return ResourceManager.GetString("ConfigurableScriptRulePropertyHasNotAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsFileHasInvalidHashtable.
        /// </summary>
        internal static string ConfigurationFileHasInvalidHashtable {
            get {
                return ResourceManager.GetString("ConfigurationFileHasInvalidHashtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsFileHasNoHashTable.
        /// </summary>
        internal static string ConfigurationFileHasNoHashTable {
            get {
                return ResourceManager.GetString("ConfigurationFileHasNoHashTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsFileNotFound.
        /// </summary>
        internal static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsKeyNotAString.
        /// </summary>
        internal static string ConfigurationKeyNotAString {
            get {
                return ResourceManager.GetString("ConfigurationKeyNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsValueNotAString.
        /// </summary>
        internal static string ConfigurationValueNotAString {
            get {
                return ResourceManager.GetString("ConfigurationValueNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsValueWrongFormat.
        /// </summary>
        internal static string ConfigurationValueWrongFormat {
            get {
                return ResourceManager.GetString("ConfigurationValueWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes all diagnostics to WriteObject..
        /// </summary>
        internal static string DefaultLoggerDescription {
            get {
                return ResourceManager.GetString("DefaultLoggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteObjects.
        /// </summary>
        internal static string DefaultLoggerName {
            get {
                return ResourceManager.GetString("DefaultLoggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge from {0} to {1} already exists..
        /// </summary>
        internal static string DigraphEdgeAlreadyExists {
            get {
                return ResourceManager.GetString("DigraphEdgeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex {0} already exists! Cannot add it to the digraph..
        /// </summary>
        internal static string DigraphVertexAlreadyExists {
            get {
                return ResourceManager.GetString("DigraphVertexAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex {0} does not exist in the digraph..
        /// </summary>
        internal static string DigraphVertexDoesNotExists {
            get {
                return ResourceManager.GetString("DigraphVertexDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine line endings as the text probably contain mixed line endings..
        /// </summary>
        internal static string EditableTextInvalidLineEnding {
            get {
                return ResourceManager.GetString("EditableTextInvalidLineEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextEdit extent not completely contained in EditableText..
        /// </summary>
        internal static string EditableTextRangeIsNotContained {
            get {
                return ResourceManager.GetString("EditableTextRangeIsNotContained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find file &apos;{0}&apos;..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the path &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file &apos;{0}&apos; is invalid because it does not contain a hashtable..
        /// </summary>
        internal static string InvalidProfile {
            get {
                return ResourceManager.GetString("InvalidProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key {0} in the settings is not a string..
        /// </summary>
        internal static string KeyNotString {
            get {
                return ResourceManager.GetString("KeyNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No loggers found..
        /// </summary>
        internal static string LoggersNotFound {
            get {
                return ResourceManager.GetString("LoggersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find rule extension &apos;{0}&apos;..
        /// </summary>
        internal static string MissingRuleExtension {
            get {
                return ResourceManager.GetString("MissingRuleExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary module location: {0}..
        /// </summary>
        internal static string ModuleDepHandlerTempLocation {
            get {
                return ResourceManager.GetString("ModuleDepHandlerTempLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be set by both positional and named arguments..
        /// </summary>
        internal static string NamedAndPositionalArgumentsConflictError {
            get {
                return ResourceManager.GetString("NamedAndPositionalArgumentsConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named arguments must always come after positional arguments..
        /// </summary>
        internal static string NamedArgumentsBeforePositionalError {
            get {
                return ResourceManager.GetString("NamedArgumentsBeforePositionalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleName must not be null..
        /// </summary>
        internal static string NullRuleNameError {
            get {
                return ResourceManager.GetString("NullRuleNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error in script definition:  {0} at line {1} column {2}..
        /// </summary>
        internal static string ParseErrorFormatForScriptDefinition {
            get {
                return ResourceManager.GetString("ParseErrorFormatForScriptDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error in file {0}:  {1} at line {2} column {3}..
        /// </summary>
        internal static string ParserErrorFormat {
            get {
                return ResourceManager.GetString("ParserErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many parser errors in {0}. Please correct them before running ScriptAnalyzer..
        /// </summary>
        internal static string ParserErrorMessage {
            get {
                return ResourceManager.GetString("ParserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many parser errors in the script definition. Please correct them before running ScriptAnalyzer..
        /// </summary>
        internal static string ParserErrorMessageForScriptDefinition {
            get {
                return ResourceManager.GetString("ParserErrorMessageForScriptDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column number cannot be less than 1..
        /// </summary>
        internal static string PositionColumnLessThanOne {
            get {
                return ResourceManager.GetString("PositionColumnLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number cannot be less than 1..
        /// </summary>
        internal static string PositionLineLessThanOne {
            get {
                return ResourceManager.GetString("PositionLineLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input position should be less than that of the invoking object..
        /// </summary>
        internal static string PositionRefPosLessThanInputPos {
            get {
                return ResourceManager.GetString("PositionRefPosLessThanInputPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Position should begin before start Position of Range..
        /// </summary>
        internal static string RangeRefPosShouldStartBeforeRangeStartPos {
            get {
                return ResourceManager.GetString("RangeRefPosShouldStartBeforeRangeStartPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start position cannot be before End position..
        /// </summary>
        internal static string RangeStartPosGreaterThanEndPos {
            get {
                return ResourceManager.GetString("RangeStartPosGreaterThanEndPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RULE_ERROR.
        /// </summary>
        internal static string RuleErrorMessage {
            get {
                return ResourceManager.GetString("RuleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find ScriptAnalyzer rules in the specified path.
        /// </summary>
        internal static string RulesNotFound {
            get {
                return ResourceManager.GetString("RulesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression Message Attribute error at line {0} in {1} : {2}.
        /// </summary>
        internal static string RuleSuppressionErrorFormat {
            get {
                return ResourceManager.GetString("RuleSuppressionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression Message Attribute error at line {0} in script definition : {1}.
        /// </summary>
        internal static string RuleSuppressionErrorFormatScriptDefinition {
            get {
                return ResourceManager.GetString("RuleSuppressionErrorFormatScriptDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any DiagnosticRecord with the Rule Suppression ID {0}..
        /// </summary>
        internal static string RuleSuppressionIDError {
            get {
                return ResourceManager.GetString("RuleSuppressionIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0}. Will use it to provide settings for this invocation..
        /// </summary>
        internal static string SettingsAutoDiscovered {
            get {
                return ResourceManager.GetString("SettingsAutoDiscovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve settings file path &apos;{0}&apos;..
        /// </summary>
        internal static string SettingsCannotFindFile {
            get {
                return ResourceManager.GetString("SettingsCannotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary should be indexable in a case-insensitive manner..
        /// </summary>
        internal static string SettingsDictionaryShouldBeCaseInsesitive {
            get {
                return ResourceManager.GetString("SettingsDictionaryShouldBeCaseInsesitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input should be a dictionary type..
        /// </summary>
        internal static string SettingsInputShouldBeDictionary {
            get {
                return ResourceManager.GetString("SettingsInputShouldBeDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings should be either a file path, built-in preset or a hashtable..
        /// </summary>
        internal static string SettingsInvalidType {
            get {
                return ResourceManager.GetString("SettingsInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse settings. Will abort the invocation..
        /// </summary>
        internal static string SettingsNotParsable {
            get {
                return ResourceManager.GetString("SettingsNotParsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings not provided. Will look for settings file in the given path {0}..
        /// </summary>
        internal static string SettingsNotProvided {
            get {
                return ResourceManager.GetString("SettingsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings object could not be resolved..
        /// </summary>
        internal static string SettingsObjectCouldNotBResolved {
            get {
                return ResourceManager.GetString("SettingsObjectCouldNotBResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using settings file at {0}..
        /// </summary>
        internal static string SettingsUsingFile {
            get {
                return ResourceManager.GetString("SettingsUsingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using settings hashtable..
        /// </summary>
        internal static string SettingsUsingHashtable {
            get {
                return ResourceManager.GetString("SettingsUsingHashtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property must be of type bool..
        /// </summary>
        internal static string SettingsValueTypeMustBeBool {
            get {
                return ResourceManager.GetString("SettingsValueTypeMustBeBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the arguments of the Suppress Message Attribute should be string constants..
        /// </summary>
        internal static string StringConstantArgumentsSuppressionAttributeError {
            get {
                return ResourceManager.GetString("StringConstantArgumentsSuppressionAttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any Targets {0} that match the Scope {1} to apply the SuppressMessageAttribute..
        /// </summary>
        internal static string TargetCannotBeFoundError {
            get {
                return ResourceManager.GetString("TargetCannotBeFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Target is specified, Scope must be specified..
        /// </summary>
        internal static string TargetWithoutScopeSuppressionAttributeError {
            get {
                return ResourceManager.GetString("TargetWithoutScopeSuppressionAttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line element cannot be null..
        /// </summary>
        internal static string TextEditNoNullItem {
            get {
                return ResourceManager.GetString("TextEditNoNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line element cannot be null..
        /// </summary>
        internal static string TextLinesNoNullItem {
            get {
                return ResourceManager.GetString("TextLinesNoNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring &apos;TypeNotFound&apos; parse error on type &apos;{0}&apos;. Check if the specified type is correct. This can also be due the type not being known at parse time due to types imported by &apos;using&apos; statements..
        /// </summary>
        internal static string TypeNotFoundParseErrorFound {
            get {
                return ResourceManager.GetString("TypeNotFoundParseErrorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing file: {0}.
        /// </summary>
        internal static string VerboseFileMessage {
            get {
                return ResourceManager.GetString("VerboseFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0} rule..
        /// </summary>
        internal static string VerboseRunningMessage {
            get {
                return ResourceManager.GetString("VerboseRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing Script Definition..
        /// </summary>
        internal static string VerboseScriptDefinitionMessage {
            get {
                return ResourceManager.GetString("VerboseScriptDefinitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongSettingsKey.
        /// </summary>
        internal static string WrongConfigurationKey {
            get {
                return ResourceManager.GetString("WrongConfigurationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid key in the settings hashtable: file {3}. Valid keys are ExcludeRules, IncludeRules and Severity..
        /// </summary>
        internal static string WrongKey {
            get {
                return ResourceManager.GetString("WrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key in the settings hashtable should be a string: line {0} column {1} in file {2}.
        /// </summary>
        internal static string WrongKeyFormat {
            get {
                return ResourceManager.GetString("WrongKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid key in the settings hashtable. Valid keys are CustomRulePath, ExcludeRules, IncludeRules, IncludeDefaultRules, RecurseCustomRulePath, Rules and Severity..
        /// </summary>
        internal static string WrongKeyHashTable {
            get {
                return ResourceManager.GetString("WrongKeyHashTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope can only be either function or class..
        /// </summary>
        internal static string WrongScopeArgumentSuppressionAttributeError {
            get {
                return ResourceManager.GetString("WrongScopeArgumentSuppressionAttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value in the settings hashtable should be a string or an array of strings: line {0} column {1} in file {2}.
        /// </summary>
        internal static string WrongValueFormat {
            get {
                return ResourceManager.GetString("WrongValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} for key {1} has the wrong data type..
        /// </summary>
        internal static string WrongValueHashTable {
            get {
                return ResourceManager.GetString("WrongValueHashTable", resourceCulture);
            }
        }
    }
}
