@{
    IncludeRules=@('PSUseApprovedVerbs',
                   'PSReservedCmdletChar',
                   'PSReservedParams',
                   'PSShouldProcess',
                   'PSUseShouldProcessForStateChangingFunctions',
                   'PSUseSingularNouns',
                   'PSMissingModuleManifestField',
                   'PSAvoidDefaultValueSwitchParameter')
}