@{
    IncludeRules=@('PSUseApprovedVerbs',
                   'PSReservedCmdletChar',
                   'PSReservedParams',
                   'PSShouldProcess',
                   'PSUseShouldProcessForStateChangingFunctions',
                   'PSUseSingularNouns',
                   'PSMissingModuleManifestField',
                   'PSAvoidDefaultValueSwitchParameter',
                   'PSAvoidUsingCmdletAliases',
                   'PSAvoidUsingWMICmdlet',
                   'PSAvoidUsingEmptyCatchBlock',
                   'PSUseCmdletCorrectly',
                   'PSUseShouldProcessForStateChangingFunctions',
                   'PSAvoidUsingPositionalParameters',
                   'PSAvoidGlobalVars',
                   'PSUseDeclaredVarsMoreThanAssignments',
                   'PSAvoidUsingInvokeExpression',
                   'PSAvoidUsingPlainTextForPassword',
                   'PSAvoidUsingComputerNameHardcoded',
                   'PSUsePSCredentialType',
                   'PSDSC*'
                   )
}
