@{
    IncludeRules=@('PSAvoidUsingCmdletAliases',
                   'PSAvoidUsingWMICmdlet',
                   'PSAvoidUsingEmptyCatchBlock',
                   'PSUseCmdletCorrectly',
                   'PSUseShouldProcessForStateChangingFunctions',
                   'PSAvoidUsingPositionalParameters',
                   'PSAvoidGlobalVars',
                   'PSUseDeclaredVarsMoreThanAssignments',
                   'PSAvoidUsingInvokeExpression')
}