# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

BeforeAll {
    $settingsFileName = 'PSScriptAnalyzerSettings.psd1'
}

Describe "New-ScriptAnalyzerSettingsFile" {
    Context "When creating a default settings file (no preset)" {
        BeforeAll {
            $testDir = Join-Path $TestDrive 'default'
            New-Item -ItemType Directory -Path $testDir | Out-Null
            $result = New-ScriptAnalyzerSettingsFile -Path $testDir
            $settingsPath = Join-Path $testDir $settingsFileName
        }

        It "Should return a FileInfo object" {
            $result | Should -BeOfType ([System.IO.FileInfo])
        }

        It "Should create the settings file" {
            $settingsPath | Should -Exist
        }

        It "Should produce a valid PSD1 that can be parsed" {
            { Import-PowerShellDataFile -Path $settingsPath } | Should -Not -Throw
        }

        It "Should contain the IncludeRules key with at least one rule" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('IncludeRules') | Should -BeTrue
            $data['IncludeRules'].Count | Should -BeGreaterThan 0
        }

        It "Should contain the ExcludeRules key" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('ExcludeRules') | Should -BeTrue
        }

        It "Should contain the Severity key" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('Severity') | Should -BeTrue
        }

        It "Should contain the CustomRulePath key" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('CustomRulePath') | Should -BeTrue
        }

        It "Should contain the IncludeDefaultRules key" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('IncludeDefaultRules') | Should -BeTrue
        }

        It "Should contain the RecurseCustomRulePath key" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('RecurseCustomRulePath') | Should -BeTrue
        }

        It "Should contain the Rules key" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('Rules') | Should -BeTrue
        }

        It "Should include all available rules in IncludeRules" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $allRules = Get-ScriptAnalyzerRule | ForEach-Object RuleName
            foreach ($rule in $allRules) {
                $data['IncludeRules'] | Should -Contain $rule
            }
        }

        It "Should place Enable first in rule settings" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '(?s)PSUseConsistentIndentation = @\{\s+Enable'
        }

        It "Should include inline comments listing valid values for constrained properties" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match "# Space, Tab"
        }

        It "Should include a comment with valid severity values" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# Information, Warning, Error, ParseError'
        }

        It "Should be usable with Invoke-ScriptAnalyzer" {
            { Invoke-ScriptAnalyzer -ScriptDefinition '"hello"' -Settings $settingsPath } | Should -Not -Throw
        }

        It "Should contain a header with the PSScriptAnalyzer version" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# PSScriptAnalyzer settings file \(\d+\.\d+\.\d+\)'
        }

        It "Should contain a header with the generation tool name" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# Generated by New-ScriptAnalyzerSettingsFile\.'
        }

        It "Should not mention a preset in the header" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Not -Match '# Based on the'
        }

        It "Should contain a section comment before IncludeRules" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# Rules to run\. When populated, only these rules are used\.'
        }

        It "Should contain a section comment before ExcludeRules" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# Rules to skip\. Takes precedence over IncludeRules\.'
        }

        It "Should contain a section comment before Severity" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# Only report diagnostics at these severity levels\.'
        }

        It "Should contain a section comment before Rules" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# Per-rule configuration\. Only configurable rules appear here\.'
        }
    }

    Context "When creating a settings file based on a preset" {
        BeforeAll {
            $testDir = Join-Path $TestDrive 'preset'
            New-Item -ItemType Directory -Path $testDir | Out-Null
            $result = New-ScriptAnalyzerSettingsFile -Path $testDir -BaseOnPreset CodeFormatting
            $settingsPath = Join-Path $testDir $settingsFileName
        }

        It "Should create the settings file" {
            $settingsPath | Should -Exist
        }

        It "Should produce a valid PSD1" {
            { Import-PowerShellDataFile -Path $settingsPath } | Should -Not -Throw
        }

        It "Should contain all top-level fields" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('IncludeRules') | Should -BeTrue
            $data.ContainsKey('ExcludeRules') | Should -BeTrue
            $data.ContainsKey('Severity') | Should -BeTrue
            $data.ContainsKey('CustomRulePath') | Should -BeTrue
            $data.ContainsKey('IncludeDefaultRules') | Should -BeTrue
            $data.ContainsKey('RecurseCustomRulePath') | Should -BeTrue
            $data.ContainsKey('Rules') | Should -BeTrue
        }

        It "Should include the preset rules in IncludeRules" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data['IncludeRules'] | Should -Contain 'PSPlaceOpenBrace'
            $data['IncludeRules'] | Should -Contain 'PSUseConsistentIndentation'
        }

        It "Should include rule configuration from the preset" {
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data['Rules'].ContainsKey('PSPlaceOpenBrace') | Should -BeTrue
            $data['Rules']['PSPlaceOpenBrace']['Enable'] | Should -BeTrue
        }

        It "Should be usable with Invoke-ScriptAnalyzer" {
            { Invoke-ScriptAnalyzer -ScriptDefinition '"hello"' -Settings $settingsPath } | Should -Not -Throw
        }

        It "Should mention the preset name in the header" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match "# Based on the 'CodeFormatting' preset\."
        }

        It "Should contain section comments" {
            $content = Get-Content -Path $settingsPath -Raw
            $content | Should -Match '# Rules to run'
            $content | Should -Match '# Rules to skip'
            $content | Should -Match '# Only report diagnostics at these severity levels'
            $content | Should -Match '# Per-rule configuration'
        }
    }

    Context "When a settings file already exists at the target path" {
        BeforeAll {
            $testDir = Join-Path $TestDrive 'exists'
            New-Item -ItemType Directory -Path $testDir | Out-Null
            Set-Content -Path (Join-Path $testDir $settingsFileName) -Value '@{}'
        }

        It "Should throw a terminating error without -Force" {
            { New-ScriptAnalyzerSettingsFile -Path $testDir -ErrorAction Stop } |
                Should -Throw -ErrorId 'SettingsFileAlreadyExists*'
        }
    }

    Context "When using -Force to overwrite an existing file" {
        BeforeAll {
            $testDir = Join-Path $TestDrive 'force'
            New-Item -ItemType Directory -Path $testDir | Out-Null
            Set-Content -Path (Join-Path $testDir $settingsFileName) -Value '@{}'
            $result = New-ScriptAnalyzerSettingsFile -Path $testDir -Force
            $settingsPath = Join-Path $testDir $settingsFileName
        }

        It "Should overwrite the existing file" {
            $settingsPath | Should -Exist
            $data = Import-PowerShellDataFile -Path $settingsPath
            $data.ContainsKey('IncludeRules') | Should -BeTrue
        }

        It "Should return a FileInfo object" {
            $result | Should -BeOfType ([System.IO.FileInfo])
        }
    }

    Context "When using -WhatIf" {
        It "Should not create the settings file" {
            $testDir = Join-Path $TestDrive 'whatif'
            New-Item -ItemType Directory -Path $testDir | Out-Null
            $settingsPath = Join-Path $testDir $settingsFileName
            # WhatIf messages are written directly to the host UI by ShouldProcess,
            # bypassing all output streams. Run in a new runspace whose default host
            # silently discards host output.
            $ps = [powershell]::Create()
            try {
                $null = $ps.AddCommand('Import-Module').AddParameter('Name', (Get-Module PSScriptAnalyzer).Path).Invoke()
                $ps.Commands.Clear()
                $null = $ps.AddCommand('New-ScriptAnalyzerSettingsFile').AddParameter('Path', $testDir).AddParameter('WhatIf', $true).Invoke()
            }
            finally {
                $ps.Dispose()
            }
            $settingsPath | Should -Not -Exist
        }
    }

    Context "When the -Path parameter points to a non-existent directory" {
        BeforeAll {
            $nestedDir = Join-Path (Join-Path (Join-Path $TestDrive 'nested') 'sub') 'folder'
            $result = New-ScriptAnalyzerSettingsFile -Path $nestedDir
            $settingsPath = Join-Path $nestedDir $settingsFileName
        }

        It "Should create the directory and the settings file" {
            $settingsPath | Should -Exist
        }
    }

    Context "When using the default path (current directory)" {
        BeforeAll {
            $testDir = Join-Path $TestDrive 'cwd'
            New-Item -ItemType Directory -Path $testDir | Out-Null
            Push-Location $testDir
            $result = New-ScriptAnalyzerSettingsFile
            $settingsPath = Join-Path $testDir $settingsFileName
        }

        AfterAll {
            Pop-Location
        }

        It "Should create the file in the current working directory" {
            $settingsPath | Should -Exist
        }
    }

    Context "Generated settings file for each preset" {
        BeforeDiscovery {
            $presets = [Microsoft.Windows.PowerShell.ScriptAnalyzer.Settings]::GetSettingPresets() |
                ForEach-Object { @{ Preset = $_ } }
        }

        It "Should produce a valid PSD1 for the '<Preset>' preset" -TestCases $presets {
            $testDir = Join-Path $TestDrive "preset-$Preset"
            New-Item -ItemType Directory -Path $testDir | Out-Null
            $settingsPath = Join-Path $testDir $settingsFileName
            New-ScriptAnalyzerSettingsFile -Path $testDir -BaseOnPreset $Preset
            { Import-PowerShellDataFile -Path $settingsPath } | Should -Not -Throw
        }
    }
}
