# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:9b06f9faaaa72fcc5c6e6021fabfa56dbc800ce5d720f91565d0881e921450f3

RUN pwsh --command Install-Module platyPS,Pester -Force
