# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

FROM mcr.microsoft.com/dotnet/core/sdk:3.1.408
    
RUN pwsh --command Install-Module platyPS,Pester -Force
